# Generated by Django 4.0.4 on 2022-06-23 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_size_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='category',
        ),
    ]
