# Generated by Django 4.0.4 on 2022-06-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_size_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name_plural': '2. brand '},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': '1. categories '},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name_plural': '3. colors '},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name_plural': '7. customer '},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': '8. orders '},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': '5. product '},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name_plural': '4. size '},
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProductAttribute',
        ),
    ]
